name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build document
      uses: devcontainers/ci@v0.2
      with:
        imageName: ghcr.io/fwilhe2/doc-devcontainer
        push: never
        runCmd: make
    - uses: actions/upload-artifact@v3
      with:
        name: my-document
        path: |
          output/
